// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NorthWind.ORM.Models
{
    public partial class YeniTablo
    {
        public int Id { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
    }
}